### ISSUE TITLE
change language button is not working in 

### ISSUE THREAD

**Issue by Izzatillo075** [byStrange/kia.uz-frontend#49]
![image](https://github.com/user-attachments/assets/a72934c9-a592-4f59-be65-476a53f2880a)
only english and english

**Comment by byStrange** [comment]
Language picker is dynamic button, it only shows supported languages configured on settings. Since translations has not implemented yet it's only showing English. However I made a quickfix for this with [bf4cec8](https://github.com/byStrange/kia.uz-frontend/commit/bf4cec8c24b0346443919b6c4b63c3f07c7a5b2f)
